HIGH_DEMAND_SECTORS = {
    "restaurantes",
    "clínicas",
    "clinicas",
    "clínicas dentales",
    "clinicas dentales",
    "veterinarias",
    "ferreterías",
    "ferreterias",
    "inmobiliarias",
    "hoteles",
    "talleres",
    "colegios",
    "academias",
    "tiendas online",
    "salones de belleza",
    "abogados",
    "aseguradoras",
    "agencias de viaje",
    "gimnasios",
}
